CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AccountRelations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Account" text NOT NULL,
    "ConnectedAccount" text NOT NULL,
    "RequestSent" boolean NULL,
    "Approved" boolean NULL,
    CONSTRAINT "PK_AccountRelations" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231226112826_primKey', '7.0.12');

COMMIT;

